export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.avif",
      username: "Safak Kocaoglu",
    },
    {
      id:2,
      profilePicture: "assets/person/2.avif",
      username: "Janell Shrum",
    },
    {
      id:3,
      profilePicture: "assets/person/3.avif",
      username: "Alex Durden",
    },
    {
      id:4,
      profilePicture: "assets/person/4.avif",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "assets/person/5.avif",
      username: "Thomas Holden",
    },
    {
      id:6,
      profilePicture: "assets/person/6.avif",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "assets/person/7.avif",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "assets/person/8.avif",
      username: "Kristen Thomas",
    },
    {
      id:9,
      profilePicture: "assets/person/9.avif",
      username: "Gary Duty",
    },
    {
      id:10,
      profilePicture: "assets/person/10.avif",
      username: "Safak Kocaoglu",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/posts/1.avif",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc:"Friends for lifetime.❤️",
      photo: "assets/posts/2.avif",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/posts/3.avif",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc:"Brother 🫂",
      photo: "assets/posts/4.avif",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/5.avif",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc:"Silent beauty🌲",
      photo: "assets/posts/6.avif",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/posts/7.avif",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc:"Best friend forever.❤️😘",
      photo: "assets/posts/8.avif",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Korean meal # Bibimbap😋",
      photo: "assets/posts/9.avif",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      desc: "Change the world by being yourself.",
      photo: "assets/posts/10.avif",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];